# Generated by Django 3.1.3 on 2020-12-20 16:31

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_admin_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('job_title', models.CharField(max_length=300, verbose_name='Job Title')),
                ('description', models.CharField(max_length=300, verbose_name='Job Description')),
                ('position', models.CharField(max_length=300, verbose_name='Position')),
                ('experience', models.CharField(max_length=300, verbose_name='Experience')),
                ('qualification', models.CharField(max_length=100, verbose_name='Qualification')),
                ('salary', models.CharField(max_length=300, verbose_name='Salary')),
                ('status', models.CharField(choices=[('', 'Select'), ('Open', 'Open'), ('Closed', 'Closed')], max_length=30, null=True, verbose_name='Job Status')),
                ('date', models.DateField(default=datetime.datetime(2020, 12, 20, 16, 31, 52, 404072, tzinfo=utc))),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.admin_detail')),
            ],
        ),
    ]
