# Generated by Django 3.1.3 on 2020-12-20 16:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_job_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_detail',
            name='image',
            field=models.FileField(null=True, upload_to='documents/', verbose_name='Logo Image'),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 20, 16, 41, 41, 993875, tzinfo=utc)),
        ),
    ]
