# Generated by Django 3.1.3 on 2020-12-21 07:46

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20201221_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='applied_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 21, 7, 46, 54, 933704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 21, 7, 46, 54, 927700, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Job_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_recceived', models.DateField()),
                ('hr_officer', models.EmailField(max_length=100)),
                ('out_come', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('apply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apply_job')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.job_detail')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_detail')),
            ],
        ),
    ]
