# Generated by Django 3.1.3 on 2020-12-23 15:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20201221_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='applied_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 23, 15, 8, 28, 126288, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 23, 15, 8, 28, 115281, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job_status',
            name='hr_officer',
            field=models.CharField(max_length=100),
        ),
    ]
