# Generated by Django 3.1.3 on 2020-12-26 09:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20201223_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='applied_date',
            field=models.DateField(default=datetime.datetime(2020, 12, 26, 9, 28, 42, 76250, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='job_detail',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 26, 9, 28, 42, 67244, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='state',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
